"""Render config.yaml's aliases, env, path and mask rules into shell snippets.

Each section is defined once in YAML and emitted for both POSIX shells (bash/zsh)
and fish, so there is no per-shell duplication to keep in sync.
"""

from __future__ import annotations

import shlex
from pathlib import Path

from .config import Config

HEADER = "# Generated by dotkit from config.yaml. Do not edit: change the config and rerun.\n"


def generated_files(config: Config, home: Path) -> dict[str, str]:
    """File name (under ~/.config/dotfiles/) -> content."""
    paths = [_expand(p, home) for p in config.path]
    env = {"DOTFILES_PROMPT": config.prompt, **config.env}
    return {
        "env.sh": HEADER + env_sh(env, paths),
        "aliases.sh": HEADER + aliases_sh(config.aliases),
        "env.fish": HEADER + env_fish(env, paths),
        "abbr.fish": HEADER + abbr_fish(config.aliases),
        "mask.sed": HEADER + mask_sed(config),
    }


def env_sh(env: dict[str, str], paths: list[str]) -> str:
    lines = [f"export {k}={shlex.quote(v)}" for k, v in env.items()]
    # Prepend in reverse so the first configured entry ends up first; skip duplicates.
    for p in reversed(paths):
        q = shlex.quote(p)
        lines.append(f'case ":$PATH:" in *:{q}:*) ;; *) PATH={q}:"$PATH" ;; esac')
    if paths:
        lines.append("export PATH")
    return _body(lines)


def aliases_sh(aliases: dict[str, str]) -> str:
    return _body(f"alias {k}={shlex.quote(v)}" for k, v in aliases.items())


def env_fish(env: dict[str, str], paths: list[str]) -> str:
    lines = [f"set -gx {k} {fish_quote(v)}" for k, v in env.items()]
    if paths:
        lines.append("fish_add_path --global --path " + " ".join(map(fish_quote, paths)))
    return _body(lines)


def abbr_fish(aliases: dict[str, str]) -> str:
    if not aliases:
        return ""
    lines = ["status is-interactive; or return"]
    lines += [f"abbr --add -- {k} {fish_quote(v)}" for k, v in aliases.items()]
    return _body(lines)


def mask_sed(config: Config) -> str:
    return _body(f"s/{_sed_escape(r.pattern, pattern=True)}/{_sed_escape(r.replace)}/g" for r in config.mask)


def fish_quote(value: str) -> str:
    """Quote for fish: single quotes, where only \\ and ' are special."""
    if value and all(c.isalnum() or c in "@%+=:,./-_" for c in value):
        return value
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _sed_escape(text: str, *, pattern: bool = False) -> str:
    """Escape the `/` delimiter (and, in replacements, `\\` and `&`)."""
    if not pattern:
        text = text.replace("\\", "\\\\").replace("&", "\\&")
    return text.replace("/", "\\/")


def _expand(path: str, home: Path) -> str:
    return str(home / path[2:]) if path == "~" or path.startswith("~/") else path


def _body(lines) -> str:
    text = "\n".join(lines)
    return text + "\n" if text else ""
