#!/usr/bin/env bash
# End-to-end checks: first install, idempotent rerun, config change, backups.
set -euo pipefail
cd "$(dirname "$0")/../.."

cfg=/tmp/e2e.yaml
cp tests/e2e/config.yaml "$cfg"
pass() { printf '\033[32mok\033[0m  %s\n' "$*"; }
fail() {
  printf '\033[31mFAIL\033[0m %s\n' "$*"
  exit 1
}
install() { ./install.sh --config "$cfg" | tee /tmp/out; }
expect() { grep -qE "$1" /tmp/out || fail "expected output matching: $1"; }

# Pre-existing state that must be backed up, not lost.
mkdir -p ~/.config/git && echo "old git config" >~/.config/git/config
ln -s /nonexistent ~/.zshrc

./install.sh --config "$cfg" plan >/dev/null # bootstraps python; plan is read-only
[[ ! -e ~/.config/dotfiles && -L ~/.zshrc ]] || fail "plan modified the system"
pass "plan is read-only"

install
expect '^Done: [1-9][0-9]* changed'
pass "first run applied changes"

install
expect '^Done: 0 changed'
pass "second run is a no-op"

[[ "$(getent passwd "$(id -un)" | cut -d: -f7)" == */fish ]] || fail "login shell is not fish"
backups=(~/.local/state/dotfiles/backups/*)
[[ "$(cat "${backups[0]}/.config/git/config")" == "old git config" ]] ||
  fail "pre-existing git config was not backed up"
[[ -L "${backups[0]}/.zshrc" && ! -L ~/.zshrc ]] || fail "symlinked .zshrc not replaced"
grep -q '# >>> dotfiles >>>' ~/.bashrc ~/.zshrc || fail "rc blocks missing"
[[ "$(git config user.email)" == test@example.com ]] || fail "git identity"
[[ "$(git config init.defaultBranch)" == main ]] || fail "shared git config not linked"
command -v gh >/dev/null || fail "apt_repos package gh not installed"
pass "shell, backups, rc blocks, git, apt repo"

# Commit checks are installed and refuse a leaked token.
grep -q "File generated by pre-commit" .git/hooks/pre-commit || fail "pre-commit hook not installed"
printf 'token = ghp_%s\n' "$(python3 -c 'import secrets; print(secrets.token_hex(18))')" >leak.txt
git add -A
if git commit -qm "should be refused" >/tmp/commit 2>&1; then fail "commit with a secret was accepted"; fi
grep -q "Detect hardcoded secrets.*Failed" /tmp/commit || fail "gitleaks did not report the secret"
git rm -q --cached leak.txt && rm leak.txt
pass "pre-commit hooks installed and block secrets"

fish -i -c 'abbr -q kgp; and type -q starship; and type -q z' 2>/dev/null || fail "fish setup"
zsh -i -c 'alias g >/dev/null && whence starship >/dev/null && echo secret42 | mask cat | grep -qx "\*\*\*\*"' \
  2>/dev/null || fail "zsh setup"
bash -i -c 'alias kgp >/dev/null && type starship >/dev/null && [[ $EDITOR == nvim ]]' 2>/dev/null ||
  fail "bash setup"
pass "fish, zsh and bash load aliases, env and tools"

for sh in bash zsh fish; do
  # shellcheck disable=SC2016 # $D and $PWD are expanded by the inner shell
  D="/tmp/e2e-$sh" "$sh" -i -c 'mkcd $D/a/b && up 2 && [ "$PWD" = "$D" ] && ll >/dev/null' 2>/dev/null ||
    fail "$sh: mkcd/up/ll"
done
tar -czf /tmp/e2e.tgz -C /etc hostname && mkdir -p /tmp/x
(cd /tmp/x && bash -i -c 'extract ../e2e.tgz' 2>/dev/null && [ -f hostname ]) || fail "extract"
pass "shared functions and extract work in every shell"

# Change the config: only the affected tasks may change.
sed -i 's/default: fish/default: zsh/; s/, zoxide: latest//; s/g: git, //' "$cfg"
install
expect '^Done: 3 changed'
expect 'set login shell to zsh'
expect 'remove zoxide'
[[ "$(getent passwd "$(id -un)" | cut -d: -f7)" == */zsh ]] || fail "login shell is not zsh"
! grep -q zoxide ~/.config/mise/config.toml || fail "zoxide still configured"
! grep -q 'alias g=' ~/.config/dotfiles/aliases.sh || fail "removed alias still rendered"
install
expect '^Done: 0 changed'
pass "config change applied exactly, then idempotent"

# Disabling a module prunes its links.
sed -i 's/modules: \[git, nvim, tmux, starship\]/modules: [git, nvim, starship]/' "$cfg"
install
[[ ! -e ~/.config/tmux/tmux.conf ]] || fail "tmux link not pruned"
pass "disabled module pruned"

# `prompt: builtin` swaps Starship for each shell's dependency-free prompt.
echo "prompt: builtin" >>"$cfg"
install
expect '^Done: 1 changed'
bash -i -c '__dotfiles_prompt; [[ $PS1 == *❯* ]]' 2>/dev/null || fail "bash builtin prompt"
zsh -i -c '[[ $PROMPT == *vcs_info* ]]' 2>/dev/null || fail "zsh builtin prompt"
fish -i -c 'fish_prompt | string match -q "*❯*"' 2>/dev/null || fail "fish builtin prompt"
pass "builtin prompt in every shell"

# Lifecycle of a new tool's config: adopt it, then a rerun finds nothing to do.
mkdir -p ~/.config/htop && echo "hide_threads=1" >~/.config/htop/htoprc
./install.sh --config "$cfg" adopt ~/.config/htop
[[ -L ~/.config/htop/htoprc && -f home/htop/.config/htop/htoprc ]] || fail "adopt did not move and link"
grep -q 'modules: \[git, nvim, starship, htop\]' "$cfg" || fail "adopt did not enable the module"
install
expect '^Done: 0 changed'
pass "adopt brings a new config under management"

echo "All end-to-end checks passed."
