from __future__ import annotations

import subprocess
from pathlib import Path

from dotkit.config import Config, MaskRule
from dotkit.render import abbr_fish, aliases_sh, env_fish, env_sh, fish_quote, generated_files, mask_sed


def test_aliases_quoted_for_each_shell():
    aliases = {"kgp": "kubectl get pods -o wide", "q": "echo 'hi'"}
    assert aliases_sh(aliases) == "alias kgp='kubectl get pods -o wide'\nalias q='echo '\"'\"'hi'\"'\"''\n"
    assert abbr_fish(aliases).splitlines()[1:] == [
        "abbr --add -- kgp 'kubectl get pods -o wide'",
        "abbr --add -- q 'echo \\'hi\\''",
    ]


def test_path_order_preserved_and_deduplicated_in_sh():
    script = env_sh({"EDITOR": "nvim"}, ["/a", "/b"]) + 'printf %s "$PATH:$EDITOR"'
    out = subprocess.run(["sh", "-c", script], env={"PATH": "/b:/usr/bin"}, capture_output=True, text=True)
    assert out.stdout == "/a:/b:/usr/bin:nvim"


def test_env_fish():
    assert env_fish({"EDITOR": "nvim"}, ["/x y"]) == (
        "set -gx EDITOR nvim\nfish_add_path --global --path '/x y'\n"
    )


def test_fish_quote_plain_words_unquoted():
    assert fish_quote("nvim") == "nvim"
    assert fish_quote("a b") == "'a b'"


def test_mask_sed_masks_text():
    cfg = Config(mask=(MaskRule(pattern="secret/[0-9]+", replace="a&b"),))
    script = mask_sed(cfg)
    out = subprocess.run(["sed", "-E", script], input="x secret/42 y", capture_output=True, text=True)
    assert out.stdout == "x a&b y"


def test_tilde_paths_expanded_and_header_present():
    files = generated_files(Config(path=("~/.local/bin",)), Path("/home/u"))
    assert set(files) == {"env.sh", "aliases.sh", "env.fish", "abbr.fish", "mask.sed"}
    assert "/home/u/.local/bin" in files["env.sh"]
    assert "export DOTFILES_PROMPT=starship" in files["env.sh"]
    assert "set -gx DOTFILES_PROMPT starship" in files["env.fish"]
    assert all(text.startswith("# Generated by dotkit") for text in files.values())
