"""Commit checks for this repo: secrets, PII, blocked words, lint and tests.

The checks themselves are defined in .pre-commit-config.yaml; this task makes sure
every clone has them installed, so a forgotten setup step can't let a secret through.
"""

from __future__ import annotations

import shutil
from functools import partial

from ..system import run
from .base import Change, Context, Task

MARKER = "File generated by pre-commit"


class Hooks(Task):
    name = "hooks"
    summary = "Install this repo's pre-commit checks (secrets, PII, blocked words, lint, tests)"

    def enabled(self, ctx: Context) -> bool:
        return ctx.config.pre_commit and (ctx.repo / ".git").is_dir()

    def packages(self, ctx: Context) -> list[str]:
        # pre-commit itself comes from pipx: distro packages are too old for current hooks.
        return ["pipx", "git"]

    def plan(self, ctx: Context) -> list[Change]:
        changes = []
        if _pre_commit(ctx) is None:
            changes.append(
                Change("install pre-commit (pipx)", partial(run, ["pipx", "install", "pre-commit"]))
            )
        hook = ctx.repo / ".git" / "hooks" / "pre-commit"
        if not (hook.is_file() and MARKER in hook.read_text(errors="ignore")):
            summary = "install the repo's commit checks (first run downloads them)"
            changes.append(Change(summary, partial(_install_hooks, ctx)))
        return changes


def _pre_commit(ctx: Context) -> str | None:
    pipx_bin = ctx.home / ".local" / "bin" / "pre-commit"
    return shutil.which("pre-commit") or (str(pipx_bin) if pipx_bin.exists() else None)


def _install_hooks(ctx: Context) -> None:
    # --install-hooks builds every checker now, so the first commit isn't slow.
    run([_pre_commit(ctx) or "pre-commit", "install", "--install-hooks"], cwd=ctx.repo)
